README.md

first-run / reset script, mainly

Updated readme with info about v0.975

---

README.md

readme more accurate info for first run

---

bin/installBluezPs3Driver.sh

Let's try out new Bluez v5.29, just released today...

Bluez v5.29

---

bin/actuallyConstructControllerConfig.sh
reference/txt/controlsMappingOverlay.txt

-Swapped autofire mapping with frame advance to prevent accidental pauses during rewinds

-Fixed autofire mapping

---

bin/usbGuidRootFilesystemSetup.sh
reference/lib/primestation_bash_functions.sh

-Updated lib to echo counted files for rsync function

-Now usbGuidRootFilesystemSetup script requires sudo / root to run

---

RetroPie/roms/settings/emulatorSettings/n64_mupen64plus_audio_output_to_hdmi.sh
bin/n64AudioOutToAnalog.sh
bin/n64AudioOutToHdmi.sh

-New n64 output to hdmi script & menu entry

-Fixed n64 output to analog script

---

RetroPie/roms/settings/emulatorSettings/n64_mupen64plus_audio_output_to_analog_3.5mm_jack.sh
RetroPie/roms/settings/emulatorSettings/n64_mupen64plus_audio_output_to_hdmi.sh
bin/n64AudioOutToAnalog.sh
bin/n64AudioOutToHdmi.sh

-Updated n64 audio scripts to not put quotes around the ini value

-Removed requirement to run as root for n64 audio scripts

---

.emulationstation/es_systems.cfg
bin/actuallyUpdatePrimestationOneQuick.sh
bin/cleanupTempFiles.sh
bin/megaInstallBinsNRoms.sh
bin/quickCreateFoldersAndLinksAndRemoveOldFiles.sh
bin/reallyQuickUpdatePrimestationFilesAndTheme.sh

-Modular quick folder creation and script cleanup and symlinking also enforced in quick and reallyquick updates and binsnroms installer

-Fixed c64 launch so can properly return without crash hopefully

---

RetroPie/roms/ports/Cave Story.sh
RetroPie/roms/ports/Darkplaces Quake.sh
RetroPie/roms/ports/Doom 1 Shareware.sh
RetroPie/roms/ports/Duke3D Shareware.sh
RetroPie/roms/ports/Minecraft.sh
RetroPie/roms/ports/Quake III Arena.sh
RetroPie/roms/ports/Quake.sh
bin/installMissingPortsFromRetroPieImage.sh
bin/quickResetPrimestationOne.sh
bin/upgrade2gMinPrimestationToFull.sh

-Updated quickReset script and upgrade 2G to 4G script

-Removed old ports scripts that have since been updated

---

RetroPie/roms/settings/installs/first_run_and_reset_primestation_one_not_quick.sh
RetroPie/roms/settings/megaModules/install_all_mega_modules.sh
RetroPie/roms/settings/megaModules/install_mega_module_binaries_pi1.sh
RetroPie/roms/settings/megaModules/install_mega_module_binaries_pi2.sh
bin/quickCreateFoldersAndLinksAndRemoveOldFiles.sh

-Enforced removal of these scripts in the centralized script to do that

-Removed some obsolete scripts from ES settings page

---

bin/megaCloudBakClearLogin.sh
bin/megaCloudBakLogin.sh
reference/lib/primestation_bash_functions.sh

-Refactored out helpful reusable methods to retrieve and store user input sensibly and create the megarc file too

-New clear login script

---

bin/bluetoothChangeAdapterMacAddress.sh
reference/lib/primestation_bash_functions.sh

-Fixed passing default value to a non-password text input (doh)

-Fixed actual dialog texts

---

bin/installPs3DriverQtSixAdWithGasiaSupportFromSources.sh

-Now altering uinput.cpp before compilation to not add the mac address to the controller name so retroarch can automatch controllers...

-Now removing both variants of the package name

---

bin/installLinuxJoystickMapper.sh
bin/joystickMapperEnable.sh

-Now attempting to enable mapper functionalities / reserve joysticks during rc.local startup phase...

-New mapper enable script to run at startup and after installation

---

reference/lib/primestation_bash_functions.sh

-No more relative paths in functionlib

---

bin/actuallyConstructControllerConfig.sh

-Fixed sega mastersystem controls so X is jump and Square is attack

---

RetroPie/roms/settings/megaModules/install_mega_module_dc_power_stone.sh
RetroPie/roms/settings/megaModules/install_mega_module_dc_resident_evil_nemesis.sh
RetroPie/roms/settings/megaModules/install_mega_module_dc_virtua_fighter_3_tournament_battle.sh
RetroPie/roms/settings/megaModules/install_mega_module_gba_roms.sh
bin/megaInstallBinsNRoms.sh
bin/megaInstallBinsNRomsLarge.sh
bin/megaInstallDcPhantasyStarOnline.sh
bin/megaInstallDcPowerStone.sh
bin/megaInstallDcResidentEvil3Nemesis.sh
bin/megaInstallDcVirtuaFighter3TB.sh
bin/megaInstallGbaRoms.sh

-Moar Dreamcast modules
-Updated Dreamcast Phantasy Star Online module to include a CD key
-New Game Boy Advance full module

-Updated binsnroms archives to include dreamcast

---

bin/dreamcast.sh

-Now enforcing pi ownership on vmus

-Formatting

---

.emulationstation/es_systems.cfg

-New Final Burn Alpha MAME launcher entry in ES to try launching mame roms with fba

-Noted MAME versions in each launcher full name

---

.emulationstation/es_systems.cfg

-Remapped fba to roms/fba folder

-Segacd try m3u playlist support

---

RetroPie/roms/settings/megaModules/install_mega_module_psx_bushido_blade_1.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_deception_3_dark_delusion.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_frogger.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_gran_turismo_1.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_gran_turismo_2_arcade_disc.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_gran_turismo_2_simulation_disc.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_metal_slug_x.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_pepsiman.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_pocket_fighter.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_tecmos_deception_1.sh
RetroPie/roms/settings/megaModules/install_mega_module_psx_tekken_3.sh
RetroPie/roms/settings/megaModules/install_mega_module_segacd_night_trap.sh
bin/megaInstallPsxBushidoBlade1.sh
bin/megaInstallPsxDeception3DarkDelusion.sh
bin/megaInstallPsxFrogger.sh
bin/megaInstallPsxGranTurismo1.sh
bin/megaInstallPsxGranTurismo2ArcadeDisc.sh
bin/megaInstallPsxGranTurismo2SimulationDisc.sh
bin/megaInstallPsxMetalSlugX.sh
bin/megaInstallPsxPepsiman.sh
bin/megaInstallPsxPocketFighter.sh
bin/megaInstallPsxTecmosDeception1.sh
bin/megaInstallPsxTekken3.sh
bin/megaInstallScdNightTrap.sh

--Sega CD: Night Trap
--PSX: Frogger
--PSX: Pocket Fighter
--PSX: Tekken 3
--PSX: Pepsiman
--PSX: Metal Slug X
--PSX: Gran turismo 1 & 2
--PSX: Tecmo's deception 1 & 3
--PSX: Bushido Blade 1

-New mega modules:

---

RetroPie/roms/settings/system/upgrade_primestation_minimal_to_full.sh
bin/hdmiAudioFix.sh
bin/hdmiAudioFixDisable.sh
bin/quickCreateFoldersAndLinksAndRemoveOldFiles.sh

-removed obsolete confusing script

-hdmi audio fix scripts now also force hdmi hotplug

---

README.md

also separated out the release changelog

Readme v1.00 beta2 info added, updated install cmd

---

RetroPie/roms/esconfig/AUDIO_OUT -> AUTO.py
RetroPie/roms/esconfig/AUDIO_OUT -> HDMI.py
RetroPie/roms/esconfig/AUDIO_OUT -> HEADPHONE.py
bin/networkFresh.sh

Script to remove wicd and clean network settings to default DHCP setup for the Network Manager and WPA Supplicant packages.

script to correct network settings to default

---

bin/finishPrimestationInstall.sh

Added Stratagus engine to possibly support *craft / warcraft / warcraft2
Fixed Apple ][ emulator maybe why not?

Fixed Doom

---

.emulationstation/es_systems.cfg

+Try to fix amiga direct disk launcher

-Cleanup of systems
